# Generated by Django 4.0.6 on 2023-02-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='passed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='unique_passed',
            field=models.ManyToManyField(to='api.passed'),
        ),
    ]
