# Generated by Django 4.0.6 on 2023-02-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passed_link_passed_link_unique_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='passed',
            field=models.IntegerField(default=0),
        ),
    ]
