# Generated by Django 4.1.6 on 2023-02-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_link_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='unique_passed',
        ),
        migrations.AddField(
            model_name='passed',
            name='link_key',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
